# Generated by Django 5.2.11 on 2026-09-24 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('EXECUTED', 'Executed'), ('PARTIALLY_EXECUTED', 'Partially Executed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.security')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('execution_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('executed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('EXECUTED', 'Executed'), ('SETTLED', 'Settled')], default='EXECUTED', max_length=15)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.order')),
            ],
        ),
        migrations.CreateModel(
            name='TradingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to='accounts.broker')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_accounts', to='accounts.investor')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trading_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='trading.tradingaccount'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='trading.trade')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerInvestorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_assignments', to='accounts.broker')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_assignments', to='accounts.investor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('broker', 'investor'), name='unique_broker_investor_assignment')],
            },
        ),
        migrations.CreateModel(
            name='BrokerSecurityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_assignments', to='accounts.broker')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_assignments', to='market.security')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('broker', 'security'), name='unique_broker_security_assignment')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='accounts.investor')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='market.security')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('investor', 'security'), name='unique_investor_security_holding')],
            },
        ),
    ]
