# Generated by Django 5.2.11 on 2026-09-24 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=150)),
                ('issue_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_units', models.PositiveBigIntegerField()),
                ('minimum_units', models.PositiveBigIntegerField()),
                ('maximum_units', models.PositiveBigIntegerField()),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='market.security')),
            ],
        ),
        migrations.CreateModel(
            name='IPOApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_units', models.PositiveBigIntegerField()),
                ('allotted_units', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('ALLOTTED', 'Allotted'), ('PARTIALLY_ALLOTTED', 'Partially Allotted'), ('NOT_ALLOTTED', 'Not Allotted')], default='PENDING', max_length=25)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_applications', to='accounts.investor')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='ipo.ipo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('investor', 'ipo'), name='unique_investor_ipo_application')],
            },
        ),
    ]
