# Generated by Django 5.2.11 on 2026-09-24 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('security_type', models.CharField(max_length=50)),
                ('isin', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities', to='market.company')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('high_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('low_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='market.security')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('security', 'trading_date'), name='unique_security_trading_date')],
            },
        ),
    ]
