# Generated by Django 5.2.11 on 2026-10-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('security_type', models.CharField(blank=True, max_length=50)),
                ('isin', models.CharField(max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.company')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('turnover', models.DecimalField(decimal_places=2, default=0, max_digits=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.security')),
            ],
            options={
                'unique_together': {('security', 'trading_date')},
            },
        ),
        migrations.CreateModel(
            name='BrokerSecurityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.broker')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.security')),
            ],
            options={
                'unique_together': {('broker', 'security')},
            },
        ),
    ]
