# Generated by Django 5.2.11 on 2026-10-07 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_name', models.CharField(max_length=255)),
                ('issue_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_units', models.BigIntegerField()),
                ('minimum_units', models.BigIntegerField()),
                ('maximum_units', models.BigIntegerField()),
                ('opening_date', models.DateField()),
                ('closing_date', models.DateField()),
                ('status', models.CharField(default='UPCOMING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='market.security')),
            ],
        ),
        migrations.CreateModel(
            name='IPOApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_units', models.BigIntegerField()),
                ('allotted_units', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.investor')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipo.ipo')),
            ],
            options={
                'unique_together': {('investor', 'ipo')},
            },
        ),
    ]
